### ISSUE TITLE
Performance degradation when activating readWriteSplitting Plugin

### ISSUE THREAD

**Issue by matheisco** [aws/aws-advanced-jdbc-wrapper#763]
### Describe the bug

Performance tests that exclusively test read operations show an approx. 3 times increase in response time when activating readWriteSplitting.

### Expected Behavior

Read performance stays the same regardless of which plugins are activated.

### What plugins are used? What other connection properties were set?

readWriteSplitting

### Current Behavior

There is a 3 times increase in response time in our application when activating readWriteSplitting.

### Reproduction Steps

The tested application uses Spring Boot and runs on my local machine. The application is connected to a Postgres cluster via
`spring.datasource.url=jdbc:aws-wrapper:postgresql://...amazonaws.com:5432/hcds?currentSchema=myschema`.
The cluster has one writer instance and one reader instance, the writer is in eu-central-1a, the reader is in eu-central-1b. The application itself uses the default Hikari connection pool.

The performance test calls the same HTTP endpoint multiple times. When invoked, this endpoint:
- calls a method annotated with `@Transactional(readOnly = true)`
- this method executes a single read-only SELECT statement, which returns one row of data
- the endpoint returns a string of data that is contained in the row

The performance test sends requests in parallel. The exact same test setup consistently leads to 3 times higher response times, as soon as the readWriteSplitting is used.

### Additional Information/Context

I tested different angles to see if I can produce a different behaviour, but it was always the same. As soon as the readWriteSplitting Plugin was in the game, the performance heavily degraded. 
Things I tested:
* Using cluster url vs using instance url in `spring.datasource.url` 
* Tested with and without [internal connection pooling](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheReadWriteSplittingPlugin.md#internal-connection-pooling), tested poolsize of 10 and 30. I also verified in the AWS console that the reader instance actually had 30 open connections.
* tested version 2.2.5 and 2.3.0 of the wrapper
* Tested if different lists of activated plugins made any difference: `readWriteSplitting`, `readWriteSplitting,failover,efm`, `readWriteSplitting,auroraConnectionTracker,failover,efm`
* To see if the connection to the reader instance was generally impacted, I deactivated all plugins and put the reader instance url in `spring.datasource.url`. This resulted in normal performance.

### The AWS Advanced JDBC Driver version used

2.2.5, 2.3.0

### JDK version used

Corretto-21.0.1.12.1

### Operating System and version

macos

**Comment by davecramer** [comment]
Any chance you can share the code. I'm very curious about this one!

**Comment by matheisco** [comment]
I've created [a basic Spring Boot application](https://github.com/matheisco/spring-boot-aws-wrapper) that reproduces the issue. The database is populated with one record, see [this sql](https://github.com/matheisco/spring-boot-aws-wrapper/blob/main/src/main/resources/init.sql).

For the testing, I let [this warum-up script](https://github.com/matheisco/spring-boot-aws-wrapper/blob/main/src/main/resources/warm-up.sh) run to make sure any pools and caches are initialized.

Then I just make a couple of manual requests with Postman to `http://localhost:8080/test/`, and I can already see that without `readWriteSplitting`, the response times shown in Postman are 150-300ms.
With `readWriteSplitting`, the response times are above 600ms.

**Comment by davecramer** [comment]
@matheisco Ok, so the issue here is that when we switch to readOnly, we have to create a new connection. Depending on your network round trip this could certainly take a couple hundred milliseconds. The solution is to use a HikariCP pool. The first few times will be slow but after that, you should not see the 200ms extra time

Thanks for the report and the sample app!

**Comment by matheisco** [comment]
I've [updated the example application](https://github.com/matheisco/spring-boot-aws-wrapper/commit/6eb8c575b3a86f5a4162c976a637184a678465bc) to use an internal connection pool, and I still observe the same behaviour. 

Maybe there is an error in my configuration? At least in the AWS management console I can see that the number of open connections on the reader instance corresponds to the value I'm specifying with `config.setMaximumPoolSize(...);`

**Comment by davecramer** [comment]
Thanks, will have a look!

**Comment by congoamz** [comment]
Hi @matheisco,

Thank you for raising this. I've been investigating the issue and there are two reasons for the decreased performance, see below. Please also note that we do not recommend using internal connection pools with Spring because by default Spring uses its own external connection pool. The following explanation assumes internal connection pools are disabled.

1. The first reason is how the @Transactional(readOnly = true) annotation works. When the annotated method is hit, Spring grabs a connection from the Hikari pool, calls conn.setReadOnly(true), executes the method, and then calls setReadOnly(false) as part of a post-method cleanup stage which restores the connection's initial session state. It then adds the connection back to the pool. The read/write splitting plugin switches between the writer and reader when setReadOnly is called. This means that every time the annotated method is hit, the plugin internally switches to the reader connection, executes the method, and then switches back to the writer. Although the reader connection will be cached after the first setReadOnly call, there is still some overhead when switching between the cached writer/reader connections, detailed in point 2. This constant switching is not an ideal use of the read/write splitting plugin because it is frequently incurring this overhead. A more ideal scenario would be if Spring called setReadOnly(true) once the first time the method was called, and continued to use the resulting reader connection on future method calls without switching back to the writer. Since Spring does not behave this way, we would like to suggest a different solution for your particular setup, detailed after point 2.

2. The second reason is due to the overhead of switching between the writer/reader connections. As noted in point 1, this overhead is incurred often when using @Transactional(readOnly = true). The largest overhead occurs when setReadOnly(true) is called for the first time on the connection, as the read/write plugin needs to internally open a new connection to the reader. After this, the reader connection will be cached and can be re-used in the future. However, there is still overhead when switching between cached connections. When switching, the read/write plugin transfers some session state between the source/target to keep this session state consistent between the two connections. For some of these session state variables, the database needs to be queried to fetch the value from the source and/or apply the value to the target. It is these database queries that consume the vast majority of the time it takes for a setReadOnly call to complete. Note too that this duration is quite dependent on the host's network. This is why adding the read/write splitting plugin added 50ms of overhead per GET request for me, but for you it added ~300ms.

Suggested solution: as noted above, the nature of @Transactional(readOnly = true) results in a non-ideal use of the read/write splitting plugin. I will update our documentation to clarify this. For your particular setup, we would like to recommend that you do not load the read/write plugin and instead use the reader cluster URL for your read operations and the writer cluster URL for your write operations. By doing this you avoid the overhead of constantly switching between connections while still spreading load across the database instances in your clusters. Please let me know if you think this configuration will work for you.

**Comment by bananayong** [comment]
Hi,

I've been following the threads regarding the performance implications of using the `@Transactional(readOnly = true)` annotation. I understand that using external connection pools can introduce certain overheads.

If I switch to using only internal connection pools and avoid external pools, will the performance issues associated with the `@Transactional(readOnly = true)` annotation still remain, or will they be resolved? Additionally, should I consider using the reader cluster URL instead of the read/write splitting plugin even if I use internal connection pools?

Thank you for your insights.

**Comment by matheisco** [comment]
@congoamz, due to other requirements, we ended up not using read write splitting. From my side, this ticket can be closed. Thank you anyways for your support!

**Comment by hsuamz** [comment]
Thank you @matheisco for getting back to us. Will be closing this issue.

If you have further questions regarding this or any other questions, please feel free to reach out again.
