### ISSUE TITLE
Support workarounds for the presence of Readers with different instance types (Amazon Aurora)

### ISSUE THREAD

**Issue by dekachiri** [aws/aws-advanced-jdbc-wrapper#949]
### Describe the feature

Support for custom endpoints or the ability to enumerate only the instance endpoints you want to use, as in previous versions of MariaDB Connector/J.

### Use Case

If you do not want to use `db-instance-4` for user access in the following clusters, the aws-advanced-jdbc-wrapper is not available.

```
db-instance-1: 4xlarge, writer
db-instance-2: 4xlarge, reader
db-instance-3: 4xlarge, reader
db-instance-4: large, reader
```

`db-instance-4` is used for analysis and batch applications and has insufficient resources for user access.

### Proposed Solution

At the moment I can't think of a good implementation method.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

2.3.5

### JDK version used

Corretto-17.0.10.7.1

### Operating System and version

Amazon Linux 2023

**Comment by aaronchung-bitquill** [comment]
Hi @dekachiri 

We can confirm that Custom Endpoint Support is a feature that is currently in our backlog and that we'll share feedback to the team for prioritization. We'll keep this ticket updated with any movement. 

Thank you!

**Comment by aaron-congo** [comment]
Hi @dekachiri,

We have recently introduced custom endpoint support via the Custom Endpoint Plugin in version 2.5.0 of the driver. Documentation for setting up the plugin can be found [here](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheCustomEndpointPlugin.md). Since this is now available, I will close this ticket, but please feel free to reopen it or create a new ticket if you encounter any problems or if this does not fulfill your use case.

Thank you!
